server:
  port: 8081

spring:
  application:
    name: livro-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    testWhileIdle: true
    url: jdbc:mysql://localhost:3306/livroservice
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      max_allowed_packet: 2000
    show-sql: true